/* == Generated by Matrix67.com == */

     #include      <stdio.h>
   main(t ,_,a)  char*a;{return
 t<1?main(*a,a[-t],"=a-1kj3gnm:q\
ebh_cf*<r.d>i^+?,()[?qzyrjuvcdefg\
h,!kbpolwxs'.t main(")&&a[-t]&&main
(t-1,_,a):t/2?_==*a?putchar(32[a])
  :_%115<36||main(t,_,a+1):main(
    0,t,"#{t{!{tzwws-w}~w#t}~\
      1qxx~hu!)xs{z?zxr<utg\
        :?1}<twywtuv3?w#q\
          <~ws#y}k#tt!x\
            :g}y:kzxv\
              {|_x")
                ;}

